name: get_started_boilerplate
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  #ui
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1

  #functionality
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  get_storage: ^2.1.1
  package_rename: ^1.7.1
  intl: ^0.19.0
  easy_localization: ^3.0.7
  flutter_gen: ^5.8.0
  equatable: ^2.0.5

  #network
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0

#on first time use run: dart pub global activate flutter_gen
#to generate assets: flutter pub run build_runner build
flutter_gen:
  assets:
    exclude:
      - assets/translations/*

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700